## Notebooks contains various ways by which we can create a numpy array.
### Here is a consolidated list what i have tried below 
### np.array
### np.zeros
### np.once
### np.full
### np.arange
### np.linespace
### np.random.rand
### np.random.randn
### np.eye
### np.loadtxt
### Using pandas dataframe

In [36]:
import numpy as np
import pandas as pd

###Creating an array from a list

In [37]:
arr=np.array([[1,2,3],[4,5,6]])
print (arr)


[[1 2 3]
 [4 5 6]]


In [38]:
#Creating an array of zeros of a given size
arr=np.zeros((3,2,2))
print (arr)
print ("----------------------------------------------------------")

#Creating an array of once of a given size
arr=np.ones((3,2,2))
print (arr)
print ("----------------------------------------------------------")

#Creating an array of given size with given number
arr=np.full((3,2,2),5)
print (arr)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
----------------------------------------------------------
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
----------------------------------------------------------
[[[5 5]
  [5 5]]

 [[5 5]
  [5 5]]

 [[5 5]
  [5 5]]]


In [39]:
#Creating an array between a range with a specific step, end exclusive
arr=np.arange(2,15,3)
print (arr)
print ("----------------------------------------------------------")

#Creating an array of a given number of elements within range start and end both inclusive
arr=np.linspace(1,10,15)
print (arr)


[ 2  5  8 11 14]
----------------------------------------------------------
[ 1.          1.64285714  2.28571429  2.92857143  3.57142857  4.21428571
  4.85714286  5.5         6.14285714  6.78571429  7.42857143  8.07142857
  8.71428571  9.35714286 10.        ]


In [40]:
#Creating an array random number within a range
arr=np.random.randn(5,10)
print (arr)
print ("----------------------------------------------------------")

#Creating an identity martix
arr=np.eye(4)
print (arr)

[[-0.71132014  0.45939712  0.1112171   0.46888264  0.08521265  0.12761527
  -0.80699792  0.75567696  0.37311783  0.46603768]
 [ 0.76454751 -0.86701926 -0.62466829  0.46109201 -0.41479612  0.26685564
   1.31106704  0.9527346  -0.42543359  0.76243286]
 [-0.05923617  0.25325763  0.03005219 -0.01018634  1.7175148   0.43323869
   1.11049345  0.35239006 -0.14243603  0.27576613]
 [-0.32381569  2.04361889 -2.01674422  0.57819085  0.87787543 -1.40936923
  -1.02690447 -0.49705965 -1.35592679  1.08727158]
 [ 0.52548418  0.194853    0.22088466 -0.70265977 -1.23574396  0.30477672
  -0.27119482  0.52195547  0.87880072  1.12162055]]
----------------------------------------------------------
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [41]:
#Creating an array from a text file
arr=np.loadtxt('Numpyarray.txt')
print (arr)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [42]:
#Reading data from csv using pandas and then creating a numpy array
df=pd.read_csv('Numpyarray.csv')
arr=df.to_numpy()
print(arr)

[[10 20 30]
 [40 50 60]]
